### ISSUE TITLE
FPGA bare-metal

### ISSUE THREAD

**Issue by nasahlpa** [lowRISC/lowrisc-chip#105]
Hi,
I am trying to get 0.6 run on the Nexys4 board to run. To start, I just want to get a bare-metal program to run on the board.
I did make bitstream, make hello, make program-updated; the bit file gets generated without errors and it is loaded to the board.
Jumper JP2 is set to QSPI and JP1 to USB; UART is connected to the PC. I expect that a message is printed on the serial port: screen /dev/ttyUSB1 115200 (dmsg showed me that USB1 is connected with FDTI chip).
But nothing happens.
Any ideas?

**Comment by jrrk** [comment]
The FTDI chip has multiple channels so you should try each of your /dev/ttyUSB* 
in turn. I don't think the allocation of the

tty numbers is systematic. Also I haven't tried screen, I always use microcom. 
There could be differences in flow control settings between these programs.

If you use the pre-made executables from our website, these are known good so 
should diagnose which is the correct port to use.

Another option you can try is to follow the lowrisc-quickstart procedure, this 
will give you gdb access to the chip which is independent of the serial port.
