### ISSUE TITLE
What is the max frequency that rocket-chip could run on xc7k325T-2?

### ISSUE THREAD

**Issue by hyf6661669** [lowRISC/lowrisc-chip#111]
I'm using a GENESYS2 board from Digilent with xc7k325T-2. The board is a little bit different from KC705 in hardware but should be able to run rocket-chip easily. In this link 
```
https://www.lowrisc.org/docs/untether-v0.2/fpga-demo
```
it says in KC705 the running frequency is 50MHz. Does anyone know the max frequency that rocket-chip with FPU could run on xc7k325T-2?

**Comment by jrrk** [comment]
I have seen figures of a 25% boost compared to Artix, but there is not a completely free choice of DDR frequencies.
