### ISSUE TITLE
LowRISC 0.5 hello bare-metal example:   undefined reference to `external_interrupt'

### ISSUE THREAD

**Issue by dnjayasinghe** [lowRISC/lowrisc-chip#115]
I followed all the procedures in explained in https://www.lowrisc.org/docs/ethernet-v0.5/environment/. However, when I execute 

> 'make hello'

 inside $TOP/fpga/board/nexys4_ddr directory. I am getting 

> syscalls.o: In function `sprintf_putch':
> $TOP/fpga/bare_metal/examples/../driver/syscalls.c:80: undefined reference to `external_interrupt'
> $TOP/fpga/bare_metal/examples/../driver/syscalls.c:101: undefined reference to `external_interrupt'
> collect2: error: ld returned 1 exit status

How do I fix this issue?

**Comment by jrrk** [comment]
Sorry about that quality issue, the hello.c program was overlooked when upgrading to interrupt mode. you can just create an empty external_interrupt function and add it to hello.c, since interrupts are not required for the hello program.

**Comment by dnjayasinghe** [comment]
Thanks.
