### ISSUE TITLE
Can‘t print Boot log by quick start 

### ISSUE THREAD

**Issue by chunxue-ding** [lowRISC/lowrisc-chip#174]
Hi，I use quick start to launch Nexys4ddr board ，When I finish the instructions ——make USB=sdc mkfs fatdisk extdisk，and Unplug the SD card, insert the SD card slot, turn on the board power switch, the busy light is flickering slowly,JP1 is USB/SD JP2 is sd，but  it still hasn't started ，nothing  happened

**Comment by jrrk** [comment]
This release doesn’t support configure from SD.

**Comment by chunxue-ding** [comment]
Thank you  for answer my question sir,I try to use Remote console installation to complete the installation ,but when i  finish the instructions —— make memstick USB=sdc ,I found only one .bit file on my SD card,and this file only 9 KB, Open text content  is   not found

**Comment by jrrk** [comment]
Perhaps your download failed for some reason. Try again after a make clean. And be sure to include a log of everything that happened if you need help, the important message may not be what you think.

**Comment by chunxue-ding** [comment]
Thank you for you advice sir , There is indeed an error in the downloaded file.After downloading the correct file，Start printing  Boot log，But he made a mistake in the open boot ，after print Load boot.bin into memory ,it print **Failed to open boot!** ,hope for you advice ,thank you very much .

**Comment by chunxue-ding** [comment]
![批注 2020-06-15 155213](https://user-images.githubusercontent.com/65884023/84636468-353d0c00-af27-11ea-96c7-6ad5983a84a8.png)

**Comment by zGitHubj** [comment]
Maybe, you can use the command make USB=sdc sdcard.img. But you must use the commad sh cardmem.sh before that.
You can verify the Makefile and cardmem.sh to customize the SD card.
Perhaps the lowrisc-quickstart has some problems. So you can use the project about https://github.com/mazsola2k/lowrisc-quickstart-modernhackers.com and use its scripts to boot your lowrisc-refreshv0.6-rc4.

**Comment by chunxue-ding** [comment]
I have tried the above methods, but it is still such a mistake

**Comment by zGitHubj** [comment]
Please contact me via zjerry940325810@gmail.com and share your some specific mistakes.
