### ISSUE TITLE
ZedBoard support in Release version 0.6

### ISSUE THREAD

**Issue by abdullahyildiz** [lowRISC/lowrisc-chip#181]
There is no ZedBoard support in Release version 0.6 and [lowrisc-fpga](https://github.com/lowRISC/lowrisc-fpga) supports ZedBoard for Debug version 0.3.

Is Release version 0.6 the final supported lowRISC-chip repository or is the repository moved somewhere else?

**Comment by jrrk** [comment]
The temporary documentation is here:

https://www.cl.cam.ac.uk/~jrrk2/docs/docs/
