### ISSUE TITLE
Simulation in ariane-v0.7 release

### ISSUE THREAD

**Issue by abdullahyildiz** [lowRISC/lowrisc-chip#190]
I couldn't find a target in Makefile to run simulation. Is there any tutorial on how to run FPGA simulation in ariane-v0.7 release?

**Comment by jrrk** [comment]
I am afraid Isim is not up to the job. You can use an external simulator such as vcs, but configuration is complicated and it is expensive for non-academic users. It seems a bit silly but running on the FPGA seems to be the most effective simulation (making use of the internal logic analyser as needed)
