### ISSUE TITLE
v0.6-rc2 :in nexys4_ddr catalogue ，when send "make boot" order, there is a complier error

### ISSUE THREAD

**Issue by HenrySearch** [lowRISC/lowrisc-chip#202]
hi sir, as the title there was a error"fpga/bare_metal/examples/../driver/syscalls.c:10:20: fatal error: memory.h: No such file or directory" and "undfie __htons error",  in this tag how to make boot program,
thanks in advance

**Comment by jrrk** [comment]
That file should be present if you followed the instructions and every step succeeds.
Perhaps the compiler you are using is a different version to the one we recommend in our documentation.

**Comment by HenrySearch** [comment]
thanks a lot , it works . and also  need to comment memory.h out.
