### ISSUE TITLE
trim branches

### ISSUE THREAD

**Issue by wsong83** [lowRISC/lowrisc-chip#36]
I suggest we should trim the useless branches after the minion-v0.4 release.
If some branches are useful but isolated, such the branches for previous releases, of course they remain untouched.
However, for the branches that used to be working attempts and have then being merged into release branches or main branch, they should be removed.
I am thinking of branches like tagpipe, tagpipe-new-toolchain, tagpipe-minion-merge, minion-system, minion-sd, eth_debug.

**Comment by asb** [comment]
Agreed, all the branches you mention sound like good candidates for deletion.

**Comment by wsong83** [comment]
Done.
