### ISSUE TITLE
ISA Version

### ISSUE THREAD

**Issue by sxu55** [lowRISC/lowrisc-chip#48]
May I ask what version of RISCV ISA does this chip support? (e.g. the latest version is spec2.2 on UCB RISCV website, but I believe this chip is derived from an older repo and maybe only support older specs)

Thanks!

**Comment by wsong83** [comment]
I think it support the v2.2 RV64G. User spec has been freezed for a long time so the old code is not that old in this sense.

**Comment by jrrk** [comment]
The main thing that is missing relative to the latest specification is compressed instructions. This option is default in the latest gcc which is one of the reasons why we have stuck to an older version for now.

**Comment by sxu55** [comment]
I see. Thanks for the answer!
