### ISSUE TITLE
Issues to dealt with later

### ISSUE THREAD

**Issue by wsong83** [lowRISC/lowrisc-chip#5]
- memory operation commands in trace debugger
- I had to manually increase tlClientXactIdBits to avoid uncached crossbar lost id field.
- test softfloat
- test snooping
- test nasti

[done] memory mapped (XIP) quad SPI flash
[done] try Alex's SPI driver inside Linux and update document (upgrade Linux to 4.6.2)
[done] ISim mem loadelf error with bbl
[done] FPGA mem loadelf unstable
[done] UART read polling and interrupt
[done] Add a wrapper to control the SD reset (power) pin
[done] Feedback from Columbia related to SPI/SD

[partially done] merge nexys video (flash and trace debugger do not work)
[partially done] Automatically add IO devices to configuration string. (waiting further information about configure string)

[NoFix] allow trace debugger to change reset boot address (use jump instead)
[NoFix] Re-factoring on-chip nasti net (wait refactoring from Berkeley)
[NoFix] Support narrower AXI in the NastiIOTileLinkIOConverter (currently does not support 64-bit IO read/write) (wait refactoring from Berkeley)

**Comment by asb** [comment]
We should perhaps split the SD power pin to a separate issue. From the looks of it, I can provide a callback function to mmc-spi as part of that driver's platform data and use that to control it.
