### ISSUE TITLE
Segmentation Error

### ISSUE THREAD

**Issue by clare7** [lowRISC/lowrisc-chip#91]
Hi, I keep facing the error when I run  the 

<<CONFIG=Nexys4DebugConfig make selftest>>
it has no problem with <<make bitstream>>
so the problems only came at make target. Any advice?

INFO: [Common 17-83] Releasing license: Implementation
write_bitstream: Time (s): cpu = 00:01:05 ; elapsed = 00:01:13 . Memory (MB): peak = 3507.039 ; gain = 0.000 ; free physical = 8960 ; free virtual = 117162
INFO: [Vivado_Tcl 4-395] Unable to parse hwdef file chip_top.hwdef
INFO: [Common 17-206] Exiting Vivado at Mon May 21 10:06:51 2018...
[Mon May 21 10:06:55 2018] impl_1 finished
wait_on_run: Time (s): cpu = 00:00:00.26 ; elapsed = 00:10:15 . Memory (MB): peak = 1052.715 ; gain = 0.000 ; free physical = 11447 ; free virtual = 119649
INFO: [Common 17-206] Exiting Vivado at Mon May 21 10:06:55 2018...
vivado -mode batch -source ../../common/script/search_ramb.tcl -tclargs lowrisc-chip-imp > search-ramb.log
python ../../common/script/bmm_gen.py search-ramb.log src/boot.bmm 128 65536
data2mem -bm src/boot.mem -bd src/boot.mem -bt lowrisc-chip-imp/lowrisc-chip-imp.runs/impl_1/chip_top.bit -o b lowrisc-chip-imp/lowrisc-chip-imp.runs/impl_1/chip_top.new.bit
/opt/Xilinx/SDK/2015.4/bin/loader: line 164: 16352 Segmentation fault      (core dumped) "$RDI_PROG" "$@"
Makefile:200: recipe for target 'lowrisc-chip-imp/lowrisc-chip-imp.runs/impl_1/chip_top.new.bit' failed
make[1]: *** [lowrisc-chip-imp/lowrisc-chip-imp.runs/impl_1/chip_top.new.bit] Error 139
make[1]: Leaving directory '/home/mmwong/Documents/lowrisc-chip/fpga/board/nexys4_ddr'
Makefile:230: recipe for target 'selftest' failed
make: *** [selftest] Error 2

**Comment by wsong83** [comment]
The error is related to the data2mem command provided by Xilinx SDK
> data2mem -bm src/boot.mem -bd src/boot.mem -bt lowrisc-chip-imp/lowrisc-chip-imp.runs/impl_1/chip_top.bit -o b lowrisc-chip-imp/lowrisc-chip-imp.runs/impl_1/chip_top.new.bit
> /opt/Xilinx/SDK/2015.4/bin/loader: line 164: 16352 Segmentation fault (core dumped) "$RDI_PROG" "$@"

I suggest you to check the grammar for this command and whether all files needed are accessible and valid (not corrupted somehow). Regenerate each file if necessary. Run the command alone in shell (without the Make/Python) can be helpful as well. If all those failed, try another version of Xilinx, (downgrade is more promising than upgrade)

**Comment by jrrk** [comment]
As Wei says, this error is usually due to an incorrect (usually empty) input file due to a failed previous stage. Try make vivado and check for errors and/or make cleanall then try again.

**Comment by clare7** [comment]
all the files are valid and available and running the command alone is successful

`data2mem -bm src/boot.mem -bd src/boot.mem -bt lowrisc-chip-imp/lowrisc-chip-imp.runs/impl_1/chip_top.bit -o b lowrisc-chip-imp/lowrisc-chip-imp.runs/impl_1/chip_top.new.bit`

i have check the `make bit-update` command and the syntax/grammar of the command is correct

**Comment by jrrk** [comment]
In that case perhaps the LD_LIBRARY_PATH variable is incorrect or some 
other environment difference between the Makefile

and the command line. This particular variable determines which version 
of system libraries will be picked up,

a common problem when a fixed binary is compiled to run on many 
different versions of Linux. However since you have managed

to work around the problem manually, you should be able to proceed with 
'make program-updated' or whatever finishing step you had in mind.

**Comment by jrrk** [comment]
Or alternatively your workstation may have insufficient memory to allow 
all the steps to complete automatically. We tend to use workstations

with about 16GBytes of RAM, and the same amount of swap space.

**Comment by clare7** [comment]
Ok thanks. It works after fixing the LD_LIBRARY_PATH issue.
